#!/usr/bin/env python3
"""Emoji for the terminal, two cells wide: tools/emoji.txt from an emoji font.

Each is drawn from Noto Color Emoji at 109 px and brought down to 11 x 10
pixels (two 6 x 10 cells, less a column between it and what follows):
a pixel is on where the emoji is, and off where it is dark or of a colour
far from its own, so a face keeps its eyes and mouth. Its colour is the
nearest of the terminal's sixteen to its own. Needs Pillow; tools/mkfont.py
then reads the text file, so `make font` does not.

    python3 tools/mkemoji.py > tools/emoji.txt
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/noto/NotoColorEmoji.ttf"
W, H = 11, 10

# The ones people use most (and the hearts in all their colours). The
# check marks stay one cell: the screen's ticks are made of them.
EMOJI = (
    "😂🤣😭😍🥰😘😊😁😀😃😄😆😅😉🙂🙃😋😛😜🤪😝🤗🤭🤫🤔🤨😐😑😶😏😒🙄😬😮😯😲😳🥺"
    "😢😥😓😩😫😤😠😡🤬😈💀☠💩🤡👻👽🤖😺😹😻😼😽🙀😿😾😴🤤😪😵🤯🥱🤠🥳😎🤓🧐"
    "😕😟🙁☹😣😖😞😔😌😇🤩😚😙😗🤐🤢🤮🤧😷🤒🤕🥵🥶🥴😱😨😰"
    "❤🧡💛💚💙💜🖤🤍🤎💗💖💕💓💞💘💝💔❣💋"
    "👍👎👌✌🤞🤟🤘🤙👈👉👆👇☝✋🤚🖐👋👏🙌👐🤲🙏🤝💪👀👁👄🖕"
    "🔥✨⭐🌟💫💥💯💢💦💨💤🎉🎊🎈🎁🎂🍰🎄🏆🥇⚽🏀🎮🎵🎶🎤🎧"
    "☀🌙🌈☔❄⚡🌹🌸🌺🌻🌷🍀🌍"
    "🍕🍔🍟🍺🍻🍷🥂☕🍿🍦🍫🍎"
    "🐶🐱🐭🐰🦊🐻🐼🐷🐸🐵🙈🙉🙊🐔🐧🦋🐝🐍🐢🐟🐬🦄"
    "🚗✈🚀🏠🏡⛪🏖⏰📅📌📍🔔🔒💡📱💻📷📚✏💰💸"
    "✅❌❗❓‼⁉⚠🚫🔴🟢🔵⚫⚪🆗🆘👑💎🎯"
    "🏃💃🕺🤷🤦🙋👶👦👧👨👩👴👵"
)

# The terminal's sixteen, as pico-os's own theme draws them (near enough).
ANSI = [(0, 0, 0), (205, 49, 49), (13, 188, 121), (229, 229, 16), (36, 114, 200),
        (188, 63, 188), (17, 168, 205), (229, 229, 229), (102, 102, 102), (241, 76, 76),
        (35, 209, 139), (245, 245, 67), (59, 142, 234), (214, 112, 214), (41, 184, 219),
        (255, 255, 255)]


def lum(p):
    return 0.3 * p[0] + 0.59 * p[1] + 0.11 * p[2]


def render(font, ch):
    im = Image.new("RGBA", (160, 136), (0, 0, 0, 0))
    ImageDraw.Draw(im).text((4, 4), ch, font=font, embedded_color=True)
    box = im.getbbox()
    if not box:
        return None
    im = im.crop(box)
    w, h = im.size
    s = min(W / w, H / h)
    nw, nh = max(1, round(w * s)), max(1, round(h * s))
    px = im.load()
    opaque = [px[x, y] for y in range(h) for x in range(w) if px[x, y][3] > 128]
    if not opaque:
        return None
    own = tuple(sum(p[i] for p in opaque) // len(opaque) for i in range(3))
    level = lum(own)
    grid = [[0] * W for _ in range(H)]
    ox, oy = (W - nw) // 2, (H - nh) // 2
    for ty in range(nh):
        for tx in range(nw):
            x0, y0 = int(tx * w / nw), int(ty * h / nh)
            x1, y1 = max(x0 + 1, int((tx + 1) * w / nw)), max(y0 + 1, int((ty + 1) * h / nh))
            total = covered = other = 0
            for y in range(y0, y1):
                for x in range(x0, x1):
                    p = px[x, y]
                    total += 1
                    if p[3] > 128:
                        covered += 1
                        far = sum((a - b) ** 2 for a, b in zip(p, own)) ** 0.5
                        if lum(p) < level * 0.5 or (far > 170 and lum(p) < level * 1.2):
                            other += 1
            if covered / total > 0.45 and other / max(covered, 1) < 0.3:
                grid[oy + ty][ox + tx] = 1
    # black and white emoji become grey and white: black would not show
    choices = [i for i in range(1, 16) if i != 0]
    colour = min(choices, key=lambda i: sum((p - q) ** 2 for p, q in zip(ANSI[i], own)))
    return grid, colour


def main():
    font = ImageFont.truetype(FONT, 109)
    seen = set()
    print("# Generated by tools/mkemoji.py: code point, colour, 10 rows of 11 pixels.")
    for ch in EMOJI:
        if ch in seen:
            continue
        seen.add(ch)
        r = render(font, ch)
        if not r:
            print(f"no glyph for U+{ord(ch):04X}", file=sys.stderr)
            continue
        grid, colour = r
        rows = " ".join("".join("1" if v else "0" for v in row) for row in grid)
        print(f"{ord(ch):05x} {colour:2d} {rows}  # {ch}")


if __name__ == "__main__":
    main()
